# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CustomerManagerApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomerManagerApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'CustomerManagerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CustomerManagerApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomerManagerApp-tvOS

  target 'CustomerManagerApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
